### ISSUE TITLE
Feature request: Easy to read error dialog boxes

### ISSUE THREAD

**Issue by Overc1ocker** [inbasic/media-converter#27]
I know how to read terminal outputs, and i love that you put a terminal read out to show what the program is doing, 

![screen shot 2017-11-15 at 4 13 16 pm](https://user-images.githubusercontent.com/31421349/32861495-dbcf7b76-ca22-11e7-8778-17cef2c58614.png)

but when the program reaches a critical error, i think you should have the program create a dialog box, like the screenshots (2 examples)

![screen shot 2017-11-15 at 4 31 52 pm](https://user-images.githubusercontent.com/31421349/32861531-f97e00f2-ca22-11e7-83ca-89560bc75e72.png)
![screen shot 2017-11-15 at 4 33 41 pm](https://user-images.githubusercontent.com/31421349/32861542-019450a2-ca23-11e7-86f8-feb98d7a0fa5.png)

**Comment by inbasic** [comment]
Thanks for the report. We now handle three critical  cases:

1. FFmpeg is not reachable
2. Destination directory is not reachable
3. Temp directory is not writeable

Since the default "window.confirm" does not support custom buttons, I just used "window.alert" for now. Honestly, I was too lazy to write a custom confirm dialog!

**Comment by Overc1ocker** [comment]
looks good!
